builders:
  constToEnumBuilder:
    import: "package:const_to_enum_generator/src/builder.dart"
    builder_factories: ["constToEnumBuilder"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: source
