name: const_to_enum_generator
description: A Dart code generator an enum for static const strings in a class.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  analyzer: ^4.4.0 # Required for working with Dart's analyzer
  build: ">=2.0.0 <3.0.0"
  source_gen: ^1.0.0 # Needed for GeneratorForAnnotation

dev_dependencies:
  build_test: ^2.1.0 # Useful for testing builders
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
